package com.rudearts.urlsource.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rudearts.urlsource.model.greendao.SiteExternal;

import com.rudearts.urlsource.model.greendao.SiteExternalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig siteExternalDaoConfig;

    private final SiteExternalDao siteExternalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        siteExternalDaoConfig = daoConfigMap.get(SiteExternalDao.class).clone();
        siteExternalDaoConfig.initIdentityScope(type);

        siteExternalDao = new SiteExternalDao(siteExternalDaoConfig, this);

        registerDao(SiteExternal.class, siteExternalDao);
    }
    
    public void clear() {
        siteExternalDaoConfig.clearIdentityScope();
    }

    public SiteExternalDao getSiteExternalDao() {
        return siteExternalDao;
    }

}
